name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency: ${{ github.workflow }}

env:
  TERM: linux

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: run-tests
        uses: ./.github/actions/tests
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
